// Fill out your copyright notice in the Description page of Project Settings.

#include "SListTableRowPin.h"
#include "TypeToolbox/DataType/DataTypeProperties.h"
#include "TypeToolboxEditor/Utility/TypeToolboxUtils.h"

void SListTableRowPin::Construct(const FArguments& InArgs, UEdGraphPin* InGraphPinObj)
{
	SListStructTypePin::FArguments Args = SListStructTypePin::FArguments();
	Args.StructViewerFilter(MakeShared<FDataTableStructFilter>());
	SListStructTypePin::Construct(Args, InGraphPinObj);
}

FText SListTableRowPin::GetComboTextValue() const
{
	if (GraphPinObj->GetDefaultAsString().IsEmpty())
	{
		return FText::FromString("None");
	}

	FTableRowSelector Result;
	FTableRowSelector::StaticStruct()->ImportText(*GraphPinObj->GetDefaultAsString(), &Result, nullptr, EPropertyPortFlags::PPF_None, GLog, FTableRowSelector::StaticStruct()->GetName());

	if (!Result.SelectedStructType)
	{
		return FText::FromString("None");
	}
	
	return FText::FromString(Result.SelectedStructType->GetName());
}

void SListTableRowPin::OnStructPicked(const UScriptStruct* PickedStruct) const
{
	SListStructTypePin::OnStructPicked(PickedStruct);

	if (!PickedStruct)
	{
		GraphPinObj->GetSchema()->ResetPinToAutogeneratedDefaultValue(GraphPinObj);
		return;
	}

	FString ValueString;
	FTableRowSelector NewPickedStruct;
	NewPickedStruct.SelectedStructType = const_cast<UScriptStruct*>(PickedStruct);
	FTableRowSelector::StaticStruct()->ExportText(ValueString, &NewPickedStruct, nullptr, nullptr, EPropertyPortFlags::PPF_None, nullptr);
	GraphPinObj->GetSchema()->TrySetDefaultValue(*GraphPinObj, ValueString);
}